import Head from 'next/head'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { Icon } from '@iconify/react';
import styles from '../styles/Success.module.css'

const Error = () => {

  const containerVariants = {
    visible: {
      x: 0,
      opacity: 1,
      transition: {
        when: "beforeChildren",
        staggerChildren: .5,
      },
    },
    hidden: {
      x: "100vw",
      opacity: 0,
      transition: {
        when: "afterChildren",
      },
    },
  }

  const childVariants = {
    visible: {
      x: 0,
      opacity: 1,
    },
    hidden: {
      x: "100vw",
      opacity: 0,
      transition : {
        type: "spring",
        mass: .7
      }
    }
  }

    return (
      
        <motion.div className={styles.container}
        >
          <Head>
            <title>Error</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <motion.main className={styles.main}
            variants={containerVariants}
            initial="hidden"
            animate="visible"        
          >
            <motion.h1 variants={childVariants} className={styles.title}>Oops ! Something&apos;s wrong.</motion.h1>
            <motion.p variants={childVariants} className={styles.description}>Don&apos;t worry. I&apos;m already taking care of it.</motion.p>
            <motion.div
              variants={childVariants} className={styles.btn}
              whileTap={{ scale: 0.9 }}
            >&larr;<Link href="/"><a>Head back.</a></Link></motion.div>
          </motion.main>
        </motion.div>
  )
}
 
export default Error;