import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="py-0 px-5 min-h-screen flex flex-col justify-between bg-red-600">
      <Head>
        <title>NEW! Home - Brima Freeman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      

    </div>
  )
}
